### ISSUE TITLE
Crash to Desktop trying to Ask OpenAI

### ISSUE THREAD

**Issue by vico93** [Krazal/nppopenai#12]
I tried to ask GPT 4 to make a simple HTML page, but Notepad++ crash after a while without producing any text.

NppOpenAI 0.2.1, NPP 8.5.7

My config (token redacted, of course):
```ini
[API]
secret_key=MY_SECRET_KEY
model=gpt-4
temperature=1
max_tokens=0
top_p=1
frequency_penalty=0
presence_penalty=0
api_url=https://api.openai.com/
[PLUGIN]
keep_question=1
total_tokens_used=0
```

**Comment by Krazal** [comment]
Thank you for your feedback! Officially GPT-4 is not supported yet, but I've made a new release with GPT-4 support.

I'd like to push/commit it to nppPluginList with the chat support together, until then the NppOpenAI v0.2.1.1 version is available here:

For 32-bit Notepad++: https://github.com/Krazal/nppopenai/releases/download/v0.2.1.1/NppOpenAI_x86.zip
SHA-256: `667ab4a1ffc69fb4889180a11e6f432326bf00fab0eb843dde0de9971e9d170e`

For 64-bit Notepad++: https://github.com/Krazal/nppopenai/releases/download/v0.2.1.1/NppOpenAI_x64.zip
SHA-256: `ee1bcd5e2fef8bb08a9133266c7407a2b1262ac2c80931740224b4676c84b0dd`

You may unzip the appropriate downloaded file to the NppOpenAI plugin folder which is by default:
`C:\Program Files (x86)\Notepad++\plugins\NppOpenAI\`

Thank you for using the plugin! I hope it will work properly.

**Comment by vico93** [comment]
Worked! Thanks a lot for this update!
