### ISSUE TITLE
Plugin crashes NPP

### ISSUE THREAD

**Issue by RALIUSINDUSTRIES** [Krazal/nppopenai#15]
I'm on windows 11, when I highlight then hit the shortcut it says "waiting for open ai's response" then it crashes NPP

**Comment by Krazal** [comment]
Hi! If you're using GPT-4 model, the same issue is possible: #12

I've updated the [nppPluginList](https://github.com/notepad-plus-plus/nppPluginList), however the files in Issue #12 are still available to download manually.
