### ISSUE TITLE
Double Line Spacing Bug in 'Keep my question' Mode with Windows EOLs

### ISSUE THREAD

**Issue by BernoulliBox** [Krazal/nppopenai#19]
I am a big fan of this plugin and use it a lot.  I've noticed a niggling issue that I was hoping you could look at.

When the plugin is operated in 'Keep my question' mode and Notepad++ is configured to use the Windows line ending characters (CR-LF), the question text is inadvertently altered to include double line spacing. Interestingly, this issue does not manifest when the editor is set to use Linux EOLs, where the original text is maintained as expected.

Hopefully you'll find time to cover this at some point, as it would significantly enhance the user experience for those of us who rely on Windows EOLs in our workflows!

Thank you for your time and for the valuable work you've done on this plugin.

**Comment by Krazal** [comment]
Thank you very much for your feedback!

I've found the source of the bug, and it seems I can fix it. (The multiline questions were not tested well with Windows line endings [CR LF].) I can upload a new release tomorrow, but I'll write here too, when it'll be available to use.

Thank you again, and have a nice day/evening!

**Comment by BernoulliBox** [comment]
Thank you for the quick and efficient resolution to the issue - the update works perfectly with Windows line ending characters (CR-LF) and the issue of double line spacing is completely resolved. I'm sure others who rely on Windows EOLs in their workflows will also benefit from this update!

The ability add a System message in a file is also super useful.  As a future improvement idea, maybe we could have multiple System Message files available, and choose among them from the NppOpenAI plugin menu - that would be a cool way to keep a list of different 'personalities' ready to work!

I like the simplicity and elegance of working with OpenAI using this plugin.  For coding, and other things too!  Like recipes for baking bread, or planning a vacation, designing electronics, -  the possibilities are endless!

**Comment by Krazal** [comment]
I'm glad to hear that the update works fine! ^^

It's a great idea about the System Messages! Last week a [new project](https://github.com/users/Krazal/projects/1) has been created, and now I've added an [Improve System Message (instructions)](https://github.com/users/Krazal/projects/1/views/1?pane=issue&itemId=52204195) task. It seems relatively easy.
