### ISSUE TITLE
The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by nissay87** [Krazal/nppopenai#26]
this error occured after shift+ctrl+o

 ---------------------------
OpenAI: Error response
---------------------------
The model `gpt-4` does not exist or you do not have access to it.
---------------------------
OK   
---------------------------

i have changed it to gpt-3.5 or gpt-3 but issue didn't solved

**Comment by nissay87** [comment]
i have tried to change the model from below site, but all models are not free, how can use it as free

https://platform.openai.com/docs/models/model-endpoint-compatibility

---------------------------
OpenAI: Error response
---------------------------
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
---------------------------
OK   
---------------------------

**Comment by Krazal** [comment]
Hi!

> The model gpt-4 does not exist

The available models are listed on the OpenAI Platform: https://platform.openai.com/docs/models
You may use `gpt-3.5-turbo` _(additional similar models are available [here](https://platform.openai.com/docs/models/gpt-3-5-turbo)),_ but currently it's recommended to use `gpt-4o`, which is the latest and most advanced model of OpenAI.


> You exceeded your current quota

Unfortunately OpenAI has a one-time “free tier” (trial?) mode which is available only for a few months after registration:
https://community.openai.com/t/understanding-api-limits-and-free-tier/498517
However you may use Ollama (see: #23) or PrivateGPT (see: #25) on localhost, but their availability has not been tested directly with NppOpenAI.

**Comment by Krazal** [comment]
Hi!

I've yesterday realized, that the `model` in the config file has been misconfigured. 😮 It has been fixed in the [latest release](https://github.com/Krazal/nppopenai/releases/tag/v0.4.0.0) *(modified `gpt-4` to `gpt-4o-mini`: “affordable and intelligent small model for fast, lightweight tasks”)* complemented with a simple chat feature.

I hope you find this useful!
