### ISSUE TITLE
More explaination for is_chat and keep_question?

### ISSUE THREAD

**Issue by chigkim** [Krazal/nppopenai#27]
Could you describe what those config options are?
Does is_chat=0 use legacy completion api and 1 use chat completion api?
Does keep_question=1 include all the previous questions and answers in prompt as context and 0 only send last question to api?

**Comment by Krazal** [comment]
Hi!

The chat feature has been released, and available in the [latest release](https://github.com/Krazal/nppopenai/releases/tag/v0.4.0.0).

I hope you find it useful!
