### ISSUE TITLE
Please, remove this hard limit of 2048 chars, or, at least, let us config it on settings file.

### ISSUE THREAD

**Issue by gedean** [Krazal/nppopenai#28]
**The selected text is too long. Please select a text shorter than 2048 characters**

**Comment by Krazal** [comment]
Hi!

Unfortunately this is a Notepad++ limitation (bug?); as described in #22 issue, Notepad++ with the `NPPM_GETCURRENTWORD` plugin message returns only the first 2048 characters (bytes) of the selection. :(

However in the next (v0.4.1.0?) release I'm planning to create a (dockable) chat message window with custom text input; if all goes well, this will allow you to enter text of practically unlimited length.

**Comment by gedean** [comment]
Thank you for reply.
