### ISSUE TITLE
The plugin makes a request by shortening my API key

### ISSUE THREAD

**Issue by YusufDurmaz** [Krazal/nppopenai#29]
![image](https://github.com/user-attachments/assets/43f9f453-6b03-4cbd-a5ef-c425ff9e421b)

The part ending with Qfh1 is not the whole of my API key, but only a part of it.

(My api key has 164 chars)

**Comment by Krazal** [comment]
Hi!

Thank you for your feedback, and sorry for the inconvenience! I've increased the acceptable length of the OpenAI API Key from 128 to 256 characters, so this should work in the latest v0.4.0.1 release:
https://github.com/Krazal/nppopenai/releases/latest

However this release is not yet available in the Notepad++ Plugin Repository, so if you'd like to install it manually, you may find useful information in the wiki (FAQ) page of the plugin:
https://github.com/Krazal/nppopenai/wiki/FAQ#question-ive-an-old-buggy-nppopenai-release-how-should-i-update

**Comment by YusufDurmaz** [comment]
Thank you for your interest. Yes, the change you made solved my problem. I also learned that I need to have at least $5 in my Openai account ito use the API (according to what I learned from Openai's forum). Maybe if you specify this in the config, it may be useful for users who try it for the first time.
