### ISSUE TITLE
[Request] Announcement

### ISSUE THREAD

**Issue by vinsworldcom** [Krazal/nppopenai#3]
I see you've added to Plugin Admin, which is how I discovered this.  So I'm assuming you're ready for "prime time" and users to start exercising this plugin.

Maybe consider an announcement in the Plugin Development category on https://community.notepad-plus-plus.org/?  That will arguably get you more "press" than it being tucked away in Plugin Admin for a user to discovery only if they peruse that list - there is "new plugins!!!" announcement on Notepad++ upgrade.

Cheers.

**Comment by Krazal** [comment]
Thank you for the tip and the info! I've created a new thread in the Plugin Development category, and I'm ready for the Community's ideas. :)

https://community.notepad-plus-plus.org/topic/24444/new-plugin-nppopenai
