### ISSUE TITLE
[feature request] - Threaded Open AI query

### ISSUE THREAD

**Issue by vinsworldcom** [Krazal/nppopenai#4]
Currently, when I highlight text and press the shortcut for "Ask OpenAI", Notepad++ freezes until the query returns and populates the text.  I'm not sure how easy it would be to thread this where the query happens and one can still use Notepad++ as they query processes?

Of course, if you continue to type and change position, then the return query results would be put in the wrong place unless you reset position.  You may also have to check to see if the user moved to a different tab.  Sure this wouldn't be easy, but a thought for a future release as development (hopefully) continues?

Again, great work - I think this has so many possibilities ...

Cheers.

**Comment by Krazal** [comment]
Thank you for your comments! I've added thread support and a loading window/dialog, but I'm still thinking about a better (more user-friendly) solution.

Have a nice day!

![loader_dialog](https://user-images.githubusercontent.com/8446933/236845093-1f8059a5-a83d-4dd4-acc0-261f351fd070.png)
